### ISSUE TITLE
Ceph storage name

### ISSUE THREAD

**Issue by blageweg** [Corsinvest/cv4pve-barc#1]
Not always "ceph" in the name.
Changed 

image_spec=$(pvesm path "$disk" | grep 'ceph' | awk '{ split($0,a,":"); print a[2]}')

to 

image_spec=$(pvesm path "$disk" | awk '{ split($0,a,"/"); print a[5]}')

**Comment by franklupo** [comment]
Can you send to me output command 
pvesm path $disk

tanks

**Comment by blageweg** [comment]
Hi.

CephStorage9:vm-101-disk-1

Thanks

**Comment by blageweg** [comment]
pvesm path CephStorage9:vm-101-disk-1
/dev/rbd/rbd/vm-101-disk-1

**Comment by franklupo** [comment]
Hi,
You have enabled the krbd.

**Comment by blageweg** [comment]
Yes, problem?

**Comment by franklupo** [comment]
I prepare a fix for this.

**Comment by blageweg** [comment]
Thanks.

I have also a request.
Backup only VM what is running on that node (qm list) so all-local.

We are running backup to local storage of every node and sync after to offside

**Comment by franklupo** [comment]
Hi,
new release https://github.com/EnterpriseVE/eve4pve-barc/releases/tag/0.1.3
  * Support krbd flag
  * Add all-^??? hostname
