### ISSUE TITLE
Getting errors during backup

### ISSUE THREAD

**Issue by mgiammarco** [Corsinvest/cv4pve-barc#12]
Hello,
in my Proxmox now eve4pve-barc is giving me these errors during backup:

```
VM 119 - ======== Ceph Image 'raid1/vm-119-disk-1' ======== 
ERROR: VM 119 - Ceph snapshot 'raid1/vm-119-disk-1@' not found in backup '/mnt/pve/backupceph/barc/119/daily/raid1.vm-119-disk-1.*'
VM 119 - Copy config
VM 124 - ======== Ceph Image 'raid1/vm-124-disk-1' ======== 
ERROR: VM 124 - Ceph snapshot 'raid1/vm-124-disk-1@' not found in backup '/mnt/pve/backupceph/barc/124/daily/raid1.vm-124-disk-1.*'
VM 124 - Copy config
VM 140 - ======== Ceph Image 'raid1/vm-140-disk-1' ======== 
ERROR: VM 140 - Ceph snapshot 'raid1/vm-140-disk-1@' not found in backup '/mnt/pve/backupceph/barc/140/daily/raid1.vm-140-disk-1.*'
VM 140 - Copy config
VM 140 - Merge diff backup '170418173107raid1.vm-140-disk-1.diff' '170507000001raid1.vm-140-disk-1.diff'
Merging image diff: 32% complete...failed.
rbd: merge-diff error
ERROR: rbd merge-diff '/mnt/pve/backupceph/barc/140/daily/170418173107raid1.vm-140-disk-1.diff' '/mnt/pve/backupceph/barc/140/daily/170507000001raid1.vm-140-disk-1.diff' '/mnt/pve/backupceph/barc/140/daily/170507000001raid1.vm-140-disk-1.diff-merged'
ERROR: VM 140 - Merge diff backup '170418173107raid1.vm-140-disk-1.diff' '170507000001raid1.vm-140-disk-1.diff' to '170507000001raid1.vm-140-disk-1.diff-merged'
VM 143 - ======== Ceph Image 'raid1/vm-143-disk-1' ======== 
ERROR: VM 143 - Ceph snapshot 'raid1/vm-143-disk-1@' not found in backup '/mnt/pve/backupceph/barc/143/daily/raid1.vm-143-disk-1.*'
VM 143 - Copy config
```
What can I do?
Thanks,
Mario

**Comment by franklupo** [comment]
Hi,
send me ls -la
/mnt/pve/backupceph/barc/119/daily/raid1.vm-119-disk-1.*
/mnt/pve/backupceph/barc/124/daily/raid1.vm-124-disk-1.*

best regards

**Comment by mgiammarco** [comment]
Sorry but in both cases:
/mnt/pve/backupceph/barc/119/daily/raid1.vm-119-disk-1.*: File o directory
non esistente
/mnt/pve/backupceph/barc/124/daily/raid1.vm-124-disk-1.*: File o directory
non esistente

I see something like:
170301174553.conf                     170520000001.conf
                    170603000001.conf                     170617000001.conf
                    170701000001.conf                     170724000001.conf
 170821000001.conf
170301174553raid1.vm-119-disk-1.img   170520000001raid1.vm-119-disk-1.diff
 170603000001raid1.vm-119-disk-1.diff  170617000001raid1.vm-119-disk-1.diff
 170701000001raid1.vm-119-disk-1.diff  170725000001.conf  170822000001.conf

....





2017-09-15 18:32 GMT+02:00 Daniele Corsini <notifications@github.com>:

**Comment by franklupo** [comment]
Ciao Marco,
che versione di Proxmox utilizzi?

**Comment by mgiammarco** [comment]
Ciao Daniele, In questo caso una 4.4 con ceph ancora Hammer. Mario                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Da: Daniele CorsiniInviato: sabato 16 settembre 2017 11:13A: EnterpriseVE/eve4pve-barcRispondi a: EnterpriseVE/eve4pve-barcCc: mgiammarco; AuthorOggetto: Re: [EnterpriseVE/eve4pve-barc] Getting errors during backup (#12)Ciao Marco,
che versione di Proxmox utilizzi?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/EnterpriseVE/eve4pve-barc","title":"EnterpriseVE/eve4pve-barc","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/EnterpriseVE/eve4pve-barc"}},"updates":{"snippets":[{"icon":"PERSON","message":"@franklupo in #12: Ciao Marco,\r\nche versione di Proxmox utilizzi?"}],"action":{"name":"View Issue","url":"https://github.com/EnterpriseVE/eve4pve-barc/issues/12#issuecomment-329956754"}}}

**Comment by franklupo** [comment]
Ciao,
mi potresti mandare la riga di comando che usi per eseguire il backup?
Non ha mai funzionato oppure e successo qualcosa?

ciau grazie

**Comment by mgiammarco** [comment]
Ciao,
ecco la riga di comando (cron):
0 0 * * * root eve4pve-barc backup
--vmid=115,118,119,124,140,143,144,145,152,158,160,117,147,163,162,133
--label='daily' --path='/mnt/pve/backupceph' --keep=60

Ho diverse installazioni del vostro script.
Nella maggior parte funziona, in un paio mi ha dato piccoli problemi come
questo ma sopportabili. Nella mia stavolta ha manifestato lo stesso errore
in metà delle vm, per questo ho pensato di segnalarvelo, anche perché il
mio workaround di solito era cancellare la cartella dei backup così
ricominciava correttamente ma non mi sembra il caso di perdere sempre i
backup vecchi.
Grazie,
Mario

2017-09-16 19:24 GMT+02:00 Daniele Corsini <notifications@github.com>:

**Comment by franklupo** [comment]
Ciao,
ottimo che lo utilizzi. ma in quante installazioni lo sui (per curiosità)?
Hai modificato le snapshot a mano su ceph? 
Hai cancellato dei file nelle directory?
Prima era schedulato ad un'altro orario?

**Comment by mgiammarco** [comment]
Ciao,
al volo su 4/5 installazioni ma credo lo mettrò sempre d'ora in poi.
In questo caso non ho modificato snapshot a mano.
Credo di avere cancellato l'intera directory col numero della macchina
quando era capitato l'altra volta (non mi ricordo più se in questa
installazione o in un'altra).
Non ho mai cambiato schedulazione, imposto daily e lascio lo script cron
così come lo imposta eve4pve.
Ah sicuramente qualche volta ho lanciato il comando a mano per fare un
backup al volo prima di operazioni importanti.
Se volete posso cancellare le cartelle delle macchine che non vanno più e
tenere traccia del problema con più cura quando ricapita.
Ho provato con: rbd -p raid1 snap ls vm-115-disk-1 con le vm che non
funzionano e noto che non ci sono neanche snapshot spuri rimasti.
Grazie,
Mario


2017-09-16 19:39 GMT+02:00 Daniele Corsini <notifications@github.com>:

**Comment by franklupo** [comment]
Ciao,
le snap su rbd non ci sono per le macchine che da problemi?
Hai lanciato un "snap purge" oppure il comando clean?
Se non ci sono più le snap questo è un problema.
Forse hai ripristinato un disco con il restore?

Grazie

**Comment by mgiammarco** [comment]
Ciao,
non ho lanciato "snap purge" neanche clean e, essendo uno dei primi server,
non ho neanche usato unprotect-snapshot
Forse ho ripristinato un disco ma qui sono saltati gli snapshot di
tantissime vm.
Forse può essere che con la migrazoine da hammer a jewel ci siano stati dei
problemi.
Chiedo ultima cosa: come faccio a tornare in una situazione gestibile?
Elimino le cartelle dai backup delle macchine senz snapshot?
Grazie,
Mario


Il giorno 17 settembre 2017 15:58, Daniele Corsini <notifications@github.com

**Comment by mgiammarco** [comment]
Lasciamo perdere cancello tutto il backup e ricomincio praticamente si sono
salvate due macchine

Il giorno 17 settembre 2017 15:58, Daniele Corsini <notifications@github.com

**Comment by franklupo** [comment]
Ciao,
penso proprio che il passaggio abbia rimosso le snap (verifico meglio nella documentazione).
Si cancella tutte le cartelle e tutto riparte.
Ho inserito un controllo che se le snap non esistono su ceph non fa backup e avvisa.

Mi piacerebbe contattarti per fare delle valutazioni sul backup la mia mail è daniele.corsini@enterpriseve.com.

Grazie mille buona giornata.
