### ISSUE TITLE
multiple disk

### ISSUE THREAD

**Issue by Ogy** [Corsinvest/cv4pve-barc#15]
Hello, please make snapshot of all disk for specific VM at same time.

I have sshfs mouted storage, with 72 MBps upload.
VM has 4x 200 GB disk, who is PV for one VG in LVM
There is a lot of minutes gap between disk snapshosts of this VM, so data will be inconsistent
Thanks for your work.

**Comment by franklupo** [comment]
Hi,
**barc** is backup for Ceph using snapshot.
For this problem with LVM storage and snapshot please contact Proxmox support.

Thanks

Best regards

**Comment by Ogy** [comment]
Hi, i know.
I'm using LVM inside OS.
Psychical volume are made from CEPH.
It doesn't matter what is inside OS, I think snapshots of all disks should be created at same time, never with hours delay between each disk.
Thanks for your time
Best regards 
Tomas

**Comment by franklupo** [comment]
Hi Tomas,
thanks for the clarification. Snapshots are created in Ceph one after the other. 
Created a snapshot export the image/diff.
Perhaps you should first create all snapshots and then export them, so there would be all the same.
What do you think about it?

Thank
Best regards

**Comment by Ogy** [comment]
Hi.
This is exactly how it should be.
First make snapshots for all disk of a VM, then export it.
Many thanks for your time.
Best regards
Tomas

**Comment by Ogy** [comment]
wow, many thanks

**Comment by franklupo** [comment]
De nada :grin: :grin:
