### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by Ogy** [Corsinvest/cv4pve-barc#17]
Hi, can you, please, add new switch .. something like: "do not touch old full images" or "data retention on FS"
VM has really huge performance issues with more snapshots, I'm investigating why.
So idea is to have 1 to 2 snapshots (keep 1) and have stored images for disaster recovery reasons.
Thanks

**Comment by franklupo** [comment]
Use --keep 9999.
Do you think about it?

The snapshor is 1 for disk

**Comment by Ogy** [comment]
wow, didn't know about it, i thought it keep N snapshots as well
many many thanks, close it
where can i buy you a drink ? :)

**Comment by franklupo** [comment]
De nada...
How many installations do you have?
I'm trying to understand the users.

Thanks

**Comment by Ogy** [comment]
gracias
i have 3 node pve cluster with, so far, 40 VMs, ceph only (ssd jurnal + sas disks), mesh networking

**Comment by franklupo** [comment]
Thanks
