### ISSUE TITLE
Can you add an option to backup/restore vm/ct configuration in the same manner as vzdump

### ISSUE THREAD

**Issue by alexskysilk** [Corsinvest/cv4pve-barc#19]
eve4pve backups are great but are of limited use for restoration if the vm config is not present; can you add an option to backup/restore the configuration along with the disk image?

**Comment by franklupo** [comment]
Hi,
barc during backup saves configuration and firewalls files in the same directory of images.
Restore is manual

Best regards

**Comment by alexskysilk** [comment]
would it be possible to build the restoral mechanism to include configuration as a user selectable option?

**Comment by franklupo** [comment]
Ok, I check how to do it.

**Comment by alexskysilk** [comment]
Thank you Frank! I also want to suggest the possibility of making vzdump compatible tarballs your default backup format; this will allow interchangeability and ability to backup/restore to different mediums while retaining the power and utility of eve4pve.
