### ISSUE TITLE
Support for image compression

### ISSUE THREAD

**Issue by apachler** [Corsinvest/cv4pve-barc#2]
I really like you backup solution.
It would be really nice if your program supports compression of images with lzo.

**Comment by plant75** [comment]
Try ZFS on the dest device, you have compression without lzo

**Comment by franklupo** [comment]
Hi,
The problem of compression is excessive CPU usage in the backup process. We recommend using a file system that already has these features like ZFS.

**Comment by apachler** [comment]
Ok, thanks!
