### ISSUE TITLE
Error in merge-diff

### ISSUE THREAD

**Issue by mgiammarco** [Corsinvest/cv4pve-barc#20]
I get this error:

VM 103 - Merge diff backup '171102000001rbd.vm-103-disk-1.diff' '171110000001rbd.vm-103-disk-1.diff'
Merging image diff: 76% complete...rbd: failed to read first diff data chunk header
Merging image diff: 76% complete...failed.
rbd: merge-diff error

Thanks in advance for any help.
Mario

**Comment by franklupo** [comment]
Hi Mario,
send me output with parameter --debug

Best regards

**Comment by mgiammarco** [comment]
Sorry I forgot --debug:

> VM 103 - Removing backup '/mnt/pve/backupCeph/barc/103/daily/171127000001rbd.vm-103-disk-1.diff'
> 2017-11-29 21:21:49 DEBUG: rm '/mnt/pve/backupCeph/barc/103/daily/171127000001rbd.vm-103-disk-1.diff'
> 2017-11-29 21:21:50 DEBUG: return 0
> VM 103 - Removing backup '/mnt/pve/backupCeph/barc/103/daily/171127103113rbd.vm-103-disk-1.diff'
> 2017-11-29 21:21:50 DEBUG: rm '/mnt/pve/backupCeph/barc/103/daily/171127103113rbd.vm-103-disk-1.diff'
> 2017-11-29 21:21:50 DEBUG: return 0
> 2017-11-29 21:21:50 DEBUG: mv '/mnt/pve/backupCeph/barc/103/daily/171127103113rbd.vm-103-disk-1.diff-merged' '/mnt/pve/backupCeph/barc/103/daily/171127103113rbd.vm-103-disk-1.diff'
> 2017-11-29 21:21:50 DEBUG: return 0
> 2017-11-29 21:21:50 DEBUG: rm -f '/mnt/pve/backupCeph/barc/103/daily/171127000001.conf'
> 2017-11-29 21:21:51 DEBUG: return 0
> VM 103 - Merge diff backup '171102000001rbd.vm-103-disk-1.diff' '171124000001rbd.vm-103-disk-1.diff'
> 2017-11-29 21:21:51 DEBUG: rbd merge-diff '/mnt/pve/backupCeph/barc/103/daily/171102000001rbd.vm-103-disk-1.diff' '/mnt/pve/backupCeph/barc/103/daily/171124000001rbd.vm-103-disk-1.diff' '/mnt/pve/backupCeph/barc/103/daily/171124000001rbd.vm-103-disk-1.diff-merged'
> Merging image diff: 53% complete...^[[A^[[A^[[A^[[A^[[B^[[Brbd: failed to read first diff data chunk header
> Merging image diff: 53% complete...failed.
> rbd: merge-diff error
> ERROR: rbd merge-diff '/mnt/pve/backupCeph/barc/103/daily/171102000001rbd.vm-103-disk-1.diff' '/mnt/pve/backupCeph/barc/103/daily/171124000001rbd.vm-103-disk-1.diff' '/mnt/pve/backupCeph/barc/103/daily/171124000001rbd.vm-103-disk-1.diff-merged'
> 2017-11-29 21:37:10 DEBUG: return 33
> ERROR: VM 103 - Merge diff backup '171102000001rbd.vm-103-disk-1.diff' '171124000001rbd.vm-103-disk-1.diff' to '171124000001rbd.vm-103-disk-1.diff-merged'
> 2017-11-29 21:37:10 DEBUG: rm -f /mnt/pve/backupCeph/barc/103/daily/171124000001rbd.vm-103-disk-1.diff-merged
> 2017-11-29 21:37:10 DEBUG: return 0
> 2017-11-29 21:37:10 DEBUG: -------------------------------------------------------
> 2017-11-29 21:37:10 DEBUG: EVE4PVE_BARC_PHASE:          backup-job-end
> 2017-11-29 21:37:10 DEBUG: EVE4PVE_BARC_VMID:           0
> 2017-11-29 21:37:10 DEBUG: EVE4PVE_BARC_PATH:           /mnt/pve/backupCeph
> 2017-11-29 21:37:10 DEBUG: EVE4PVE_BARC_LABEL:          daily
> 2017-11-29 21:37:10 DEBUG: EVE4PVE_BARC_KEEP:           6
> 2017-11-29 21:37:10 DEBUG: EVE4PVE_BARC_SNAP_NAME:      -
> 2017-11-29 21:37:10 DEBUG: EVE4PVE_BARC_BACKUP_FILE:    -
> 2017-11-29 21:37:10 DEBUG: -------------------------------------------------------
>
