### ISSUE TITLE
error with multiple disks

### ISSUE THREAD

**Issue by schalt** [Corsinvest/cv4pve-barc#21]
Hi,

thanks for this project! We have two pve/ceph cluster on 4.4
After update eve4pve-barc to version 1.2.7 the second on third disks from a VM have errors.

We see this error in debug output:
VM 906 - Ceph last snapshot 'ceph_kvm/vm-906-disk-3' not found!

in the barc directory:

-rw-r--r-- 1 root users 214748364800 Nov 28 10:19 171128094501ceph_kvm.vm-906-disk-1.img
-rw-r--r-- 1 root users 214748364800 Nov 28 10:53 171128094501ceph_kvm.vm-906-disk-3.img
-rw-r----- 1 root users          359 Nov 28 10:53 171128094501.conf
-rw-r--r-- 1 root users    535279487 Nov 28 11:13 171128110001ceph_kvm.vm-906-disk-1.diff
-rw-r--r-- 1 root users     77719858 Nov 28 11:20 171128110001ceph_kvm.vm-906-disk-3.diff
-rw-r----- 1 root users          359 Nov 28 11:20 171128110001.conf
-rw-r--r-- 1 root users    750399017 Nov 28 15:07 171128121001ceph_kvm.vm-906-disk-1.diff
-rw-r----- 1 root users          359 Nov 28 15:21 171128121001.conf
-rw-r--r-- 1 root users   1122160106 Nov 28 21:10 171128183001ceph_kvm.vm-906-disk-1.diff
-rw-r----- 1 root users          359 Nov 28 21:10 171128183001.conf
-rw-r--r-- 1 root users    370376380 Nov 28 23:05 171128230001ceph_kvm.vm-906-disk-1.diff
-rw-r----- 1 root users          359 Nov 28 23:05 171128230001.conf
-rw-r--r-- 1 root users    197851087 Nov 28 23:10 171128230801ceph_kvm.vm-906-disk-1.diff
-rw-r----- 1 root users          359 Nov 28 23:10 171128230801.conf

have anyone the same problem?

**Comment by franklupo** [comment]
Hi,
you have removed snapshot at image ceph_kvm/vm-906-disk-3?

**Comment by schalt** [comment]
hi,
no we dont remove the snap from vm-906-disk-3. The first eve4pve-barc job running und create the .img files from the disks. But the diffs make problems on our cluster

**Comment by franklupo** [comment]
The cron execute more barc?
What is the schedulation?

**Comment by schalt** [comment]
we have a job with 30 vms and lxc container.The big job have errors with seperate vms (906).
We have noch error when 906 run alone in a job...

**Comment by schalt** [comment]
All error vms run on a seperate job with only one vm fine.
Have you any idear why?

**Comment by franklupo** [comment]
> Have you any idear why?
**No**

List snapshots on image ceph_kvm/vm-906-disk-3,
