### ISSUE TITLE
Backup VMs per pool

### ISSUE THREAD

**Issue by black444** [Corsinvest/cv4pve-barc#23]
Is it possible to schedule backups by pool? It will give feature to add VM to pool and backup would be made automatically.

**Comment by franklupo** [comment]
Hi,
now it is not possible.
But it's interesting. I check how it can be done.

Best regards

**Comment by franklupo** [comment]
Hi,
I'm testing the new feature of saving an entire pool.
If all goes well within a few days we will release the new version.

Best regards

**Comment by franklupo** [comment]
Hi,
whole pool, do we mean that the VMs in the pool will be saved?

Best regards

**Comment by franklupo** [comment]
New version 0.1.9
