### ISSUE TITLE
How to recover space when backup is full

### ISSUE THREAD

**Issue by mgiammarco** [Corsinvest/cv4pve-barc#24]
Hello,
I have this problem: if the backup medium became almost full you cannot recover the situation.
I think: I reduce the number of copies so it merges the old ones and I save space
Unfortunately if the backup space is almost full the merge operation cannot complete (because it needs some free space) and so I have no ways to recover.

**Comment by franklupo** [comment]
Hi,
to reduce the number of backups use the clean command with -keep.
The problem is that it has to create a new file and only at the end it is removed.
It is just "rbd merge-diff" that works like that.
And that's the problem?
