### ISSUE TITLE
Use borg backup

### ISSUE THREAD

**Issue by mgiammarco** [Corsinvest/cv4pve-barc#25]
I know this is a big change but I ask it anyways.
The standard proxmox backup is full only so it is not very helpful.
Your solution is great because it saves only diffs so I can maintain a long history.
There are two remaining problems:
1) if I have, for example, 40 backups, and I start a restore it is very long because it need to start from first file and then merge all 40 files over it
2) if a vm saves a lot of data I have big diffs and so I can keep short history.

Using borg to save snapshots will solve point 1, point 2 and also deduplicate data saving even more space to keep even more history.

**Comment by franklupo** [comment]
Hi,
I use ZFS with deduplication.
Is not a good idea?

Best regards

**Comment by franklupo** [comment]
Hi,

> if I have, for example, 40 backups, and I start a restore it is very long because it need to start from first file and then merge all 40 files over it

per migliorare importazione si setta --rbd-concurrent-management-ops ma il rischio poi e di rallentare tutto.

Best regards

**Comment by franklupo** [comment]
Hi,

> if I have, for example, 40 backups, and I start a restore it is very long because it need to start from first file and then merge all 40 files over it

How can you speed up this with borg?

Best regards

**Comment by mgiammarco** [comment]
I will not use  incremental backups. Borg saves space because it has a new
style  deduplication engine that is used also as a diff/incremental backups
strategy.
So I can ask borg to restore directly latest image and not build it
replaying 40 diffs.

2018-02-12 19:17 GMT+01:00 Daniele Corsini <notifications@github.com>:

**Comment by franklupo** [comment]
You must always export the whole image.
I must verify.
Backy2 maybe has something better.

**Comment by mgiammarco** [comment]
Yes unfortunately you must always export whole image. I will check backy2
too.

2018-02-13 11:29 GMT+01:00 Daniele Corsini <notifications@github.com>:

**Comment by mgiammarco** [comment]
I have looked at backy2 and I aeree it is better than borg because it is
rbd specific

Il mar 13 feb 2018, 11:29 Daniele Corsini <notifications@github.com> ha
scritto:

**Comment by franklupo** [comment]
I'm thinking of a version with integrated backy2.
I'll think about it.

Best regards

**Comment by mgiammarco** [comment]
I have also looked at rdiff-backup and rsnapshot for their reverse diff
protocol. Unfortunately they are not integrated with ceph like backy2 that
is the Best choice

Il mar 13 feb 2018, 11:29 Daniele Corsini <notifications@github.com> ha
scritto:
