### ISSUE TITLE
Compression

### ISSUE THREAD

**Issue by franklupo** [Corsinvest/cv4pve-barc#26]
Hi guys,
I'm going to add compression support.
The features involved are:
- backup
- restore
- assemble

The points are:
- possibility to choose which compression / decompresisone to use lz4, gz, ..
- implement compression and decompression in pipes
- existing backups how to proceed if one wants to switch to compression?

I accept changes and new ideas.

Thank you all

W Italy :grin:

**Comment by Ogy** [comment]
Hello, please add it as opt-in.
I won't use it, because i have ZFS backend, where compression and 
deduplication is used.

Thanks

Dne 3.2.2018 v 12:23 Daniele Corsini napsal(a):

**Comment by nibblerrick** [comment]
As you closed this, have you abandoned the idea or will you still add it?
Great tool btw, thanks for that!

**Comment by franklupo** [comment]
Hi,
new version in progress.

Best Regards
