### ISSUE TITLE
Support for backing on all VM on specified Proxmox node

### ISSUE THREAD

**Issue by apachler** [Corsinvest/cv4pve-barc#3]
It would be nice if there is the possibility to define that your program only backup the VMs/CTs that are located on that node the program is started.

This is usefull for a clustered solution, imagine that you have a cluster of 5 nodes. So i want to run the backup job on every node to make sure we have no single point of failure. But, we need a logic to not concurrently backup the images. So the easiest would be that each backup job would only backup the VMs/CTs that are located on the node where the backup job is running.

If we run clustered and a node fails, the VMs/CTs get moved to another node by HA. Therefore we always backup all VMs/CTS. 

I think this would be a great addition to your product.

Best regards from Austria ;)
Andreas

**Comment by blageweg** [comment]
Already in it -> eve4pve-barc backup --vmid=all-nodename --label='daily' --path='/mnt/backup' --keep=5

**Comment by apachler** [comment]
Sry that i did not saw it! Nice one!
