### ISSUE TITLE
freeze fs before snapshots

### ISSUE THREAD

**Issue by aderumier** [Corsinvest/cv4pve-barc#30]
Hi,to have consistency, we need to freeze/unfreeze the filesystem if qemu-agent is available.
(Proxomox implemented it with backup and snapshots)

#qm agent <vmid> fsfreeze-freeze
do the snasphot of all drives
#qm agent <vmid> fsfreeze-thaw

**Comment by franklupo** [comment]
Good idea

**Comment by mhubig** [comment]
You could use something like this instead of `rbd snap create` to make the snapshot:

`pvesh create /nodes/pve-node-01/qemu/100/snapshot -snapname test -vmstate 0`

**Comment by franklupo** [comment]
Hi,
Thanks for the idea.
I'm reworking the new version. Your solution does not let you know when the snapshot is over. You could analyze the task but with the bash commands it's complicated. I'm developing a cli in a new language.
The new version uses APIs and takes Proxmox snapshots.

Best regards

**Comment by mhubig** [comment]
Good news, I'm really looking forward to it! Are you using Python?

BTW: Thank you for the good work!

**Comment by franklupo** [comment]
Hi,
no, C# .Net Core

**Comment by lephisto** [comment]
Done here: https://github.com/lephisto/cv4pve-barc/commit/92bd791e0dd34d7bccdfd85745d74f6bd17da265
