### ISSUE TITLE
Restored image unusable

### ISSUE THREAD

**Issue by normanu** [Corsinvest/cv4pve-barc#32]
Restored image does not work for LXC containers.

Getting error,
Mar 27 12:15:04 nod1 kernel: rbd: image vm-104-disk-1-new: image uses unsupported features: 0x38

**Comment by franklupo** [comment]
Hi,
the problem are the features in rbd image see #4. 

> rbd feature disable ceph-lxc/vm-10X-disk-1 exclusive-lock, object-map, fast-diff, deep-flatten

**Comment by normanu** [comment]
Yes that fixed it!
