### ISSUE TITLE
Error When it's already present a Proxmox Web Interf snap

### ISSUE THREAD

**Issue by plant75** [Corsinvest/cv4pve-barc#4]
Hello, very very nice script! (Complimenti .. sono di Ravenna :-)

I have this issue if i have a previus Snapshot created by Web Interf.:

rbd: failed to create snapshot: (17) File exists
ERROR: rbd snap create ceph-lxc/vm-100-disk-1@barcdaily17032813410

Grazie!

**Comment by plant75** [comment]
I have also an error when i try to start a restored LXC vm:

 eve4pve-barc restore --vmid=100 --label='daily' --path=/STORAGE/CEPH_BK
Start restore process
Inital import 170328132844ceph-lxc.vm-100-disk-1.img
Importing image: 100% complete...done.
Differential /STORAGE/CEPH_BK/barc/100/daily/170328133910ceph-lxc.vm-100-disk-1.diff
Importing image diff: 100% complete...done.
Differential /STORAGE/CEPH_BK/barc/100/daily/170328134039ceph-lxc.vm-100-disk-1.diff
Importing image diff: 100% complete...done.
Differential /STORAGE/CEPH_BK/barc/100/daily/170328134105ceph-lxc.vm-100-disk-1.diff
Importing image diff: 100% complete...done.
Differential /STORAGE/CEPH_BK/barc/100/daily/170328134432ceph-lxc.vm-100-disk-1.diff
Importing image diff: 100% complete...done.
Removing all snapshots: 100% complete...done.
Backup ceph-lxc.vm-100-disk-1 restored in ceph-lxc/vm-105-disk-1 with success!
Consider to manually create VM/CT and change config file from backup adapting restored image.
-----------------------------------------------------------------------------

I have copied and adapted the conf file:

root@n1:/etc/pve/nodes/n1/lxc# cat 105.conf 
arch: amd64
cores: 4
hostname: t5
memory: 4096
net0: name=eth0,bridge=vmbr0,gw=192.168.1.1,hwaddr=5A:60:72:1F:86:A1,ip=192.168.1.61/24,type=veth
ostype: debian
rootfs: ceph-lxc:vm-105-disk-1,size=42G
swap: 512

------------------------------------------------------------------------------------

But i can't start it:

Mar 28 14:04:33 n1 systemd[1]: Failed to start LXC Container: 105.
-- Subject: Unit lxc@105.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit lxc@105.service has failed.
-- 
-- The result is failed.
Mar 28 14:04:33 n1 systemd[1]: Unit lxc@105.service entered failed state.
Mar 28 14:04:33 n1 pct[3263]: command 'systemctl start lxc@105' failed: exit code 1
Mar 28 14:04:33 n1 pct[3262]: <root@pam> end task UPID:n1:00000CBF:0099CB2D:58DA514B:vzstart:105:root@pam: command 'systemctl start 

------------------------------------------------------------------------------------

Grazie!

**Comment by plant75** [comment]
Work around:
after restore:
rbd feature disable ceph-lxc/vm-10X-disk-1  exclusive-lock, object-map, fast-diff, deep-flatten

**Comment by franklupo** [comment]
Fix the problem adding the ability to use the hook script when restoring.

**Comment by franklupo** [comment]
Hi,
new release 0.1.4.

- Added command **reset** remove all snap from Ceph image
- Added parameter **--unprotect-snap**
- Added hook for restore
