### ISSUE TITLE
Can't remove container after trying backup

### ISSUE THREAD

**Issue by ericfri** [Corsinvest/cv4pve-barc#5]
Hey there,

I decided to try using your backup program, and so far it looks pretty good. I am however having an issue after backing up a couple of containers. I can't delete them from the Proxmox GUI, I get an error that says "rbd snap purge 'vm-100-disk-1' error: Removing all snapshots: 0% complete...failed"

I've tried migrating the container to a different node in the cluster but that didn't help. At this point I'm not sure what else to try.

**Comment by ericfri** [comment]
I just tried from the command line with:

> rbd rm ceph-lxc/vm-101-disk-1

and it returned

> 2017-03-30 14:45:17.347216 7fa032380d40 -1 librbd: image has snapshots - not removing
> Removing image: 0% complete...failed.
> rbd: image has snapshots - these must be deleted with 'rbd snap purge' before the image can be removed.
> 

so I tried

> rbd snap purge ceph-lxc/vm-101-disk-1

and it returned

> Removing all snapshots: 0% complete...failed.
> rbd: snapshot 'barccpanel03170330023653' is protected from removal.

**Comment by ericfri** [comment]
Ok, got it. I had to manually unprotect each snapshot, then I could purge them.

> rbd --pool ceph-lxc snap unprotect --image vm-101-disk-1 --snap barcdaily170330030203

**Comment by franklupo** [comment]
Hi,
The creation of snapshots is performed with protected mode, to avoid accidental deletion. Proxmox unprotect only the snapshos he knows.

The idea is to add parameter to specify if snapshot will be created in a protected/unprotected mode.  
What do you think about it?

thank you

**Comment by ericfri** [comment]
I like the idea of protected mode, but if there was a way to disable the protection manually so Proxmox could delete the container would be nice.

So for example, you have protected mode on, do your backups for however long, then say you want to delete the container, have a way to disable the protection on all the snapshots at once, instead of doing them one-by-one.

**Comment by franklupo** [comment]
Hi,
new release 0.1.4.

- Added command **reset** remove all snap from Ceph image
- Added parameter **--unprotect-snap**
- Added hook for restore
