### ISSUE TITLE
Housekeeping deletes initial Images

### ISSUE THREAD

**Issue by KaiFischer** [Corsinvest/cv4pve-barc#50]
After backup a VM with 3 disks, 2 of 3 images was deleted by housekeeping.

eve4pve-barc backup --vmid=all --label='daily' --path=/backup --renew=0d --retain=0d

VM 101 - ======== Start backup VMID 101 ========
...
VM 101 - Export initial '/backup/barc/101/backup3daily/20200212071936cold-storage.vm-101-disk-3.img'
VM 101 - Size 8.00 GiB Uncompressed: 8.00 GiB Compressionratio 1:1
VM 101 - Export initial '/backup/barc/101/backup3daily/20200212071936cold-storage.vm-101-disk-1.img'
VM 101 - Size 120.00 GiB Uncompressed: 120.00 GiB Compressionratio 1:1
VM 101 - Export initial '/backup/barc/101/backup3daily/20200212071936cold-storage.vm-101-disk-2.img'
VM 101 - Size 25.00 GiB Uncompressed: 25.00 GiB Compressionratio 1:1
VM 101 - -------- Copy config --------
VM 101 - -------- Housekeeping --------
VM 101 - Houskeeping deleting: /backup/barc/101/backup3daily/20200212071936cold-storage.vm-101-disk-2.img
VM 101 - Houskeeping deleting: /backup/barc/101/backup3daily/20200212071936cold-storage.vm-101-disk-1.img
VM 102 - ======== Start backup VMID 102 ========

**Comment by franklupo** [comment]
Hi,
why use  --renew=0d --retain=0d?

best regards

**Comment by KaiFischer** [comment]
Hi,

to keep only one image without diff that i can mount the image without merging the last diff. For history i use ZFS snapshots.

best regards

**Comment by lephisto** [comment]
I could make sure that the last remaining image is not deleted. 

Thinking about that..

**Comment by lephisto** [comment]
I added the option to use --renew=0 --retain=1 to make full every time and keep one.
