### ISSUE TITLE
EFI disks are skipped

### ISSUE THREAD

**Issue by alyarb** [Corsinvest/cv4pve-barc#59]
Hi, thank you for a great tool.

I have a macOS system that I want to make sure is backed up with barc.

It has a SATA disk, an IDE disk, and an EFI disk. All of them are Ceph RBD images, but barc always skips the EFI disk with no message at all.

The EFI disk is vm-102-disk-1. It will only backup disk-0 and disk-2.

Thanks for looking. I will include the barc log below, and the QEMU conf below that:

ACTION: Backup
Start backup 2020-05-06 17:55:43
VM 102 - ======== Start backup VMID 102 (macOS) ========
VM 102 - -------- Snapshots Disks VMID 102--------
VM 102 - Issuing fsfreeze-freeze to 102 on virtual37
QEMU guest agent is not running
ERROR: ssh root@virtual37 /usr/sbin/qm guest cmd 102 fsfreeze-freeze
VM 102 - No previous backup: issueing full run for cephRBD:vm-102-disk-2
VM 102 - Creating snapshot cephRBD/vm-102-disk-2@barcdaily20200506175543
VM 102 - !!!!! >>> UNPROTECTED SNAPSHOT cephRBD/vm-102-disk-2@barcdaily20200506175543 <<< !!!!!
VM 102 - No previous backup: issueing full run for cephRBD:vm-102-disk-0
VM 102 - Creating snapshot cephRBD/vm-102-disk-0@barcdaily20200506175543
VM 102 - !!!!! >>> UNPROTECTED SNAPSHOT cephRBD/vm-102-disk-0@barcdaily20200506175543 <<< !!!!!
VM 102 - Issuing fsfreeze-thaw to 102 on virtual37
QEMU guest agent is not running
ERROR: ssh root@virtual37 /usr/sbin/qm guest cmd 102 fsfreeze-thaw
VM 102 - -------- Export images --------
VM 102 - Export initial '/mnt/pve/B2.C4-J/guest_backups//barc/102/daily/20200506175543cephRBD.vm-102-disk-2.img.zz'
VM 102 - excmd: rbd export --rbd-concurrent-management-ops 10 cephRBD/vm-102-disk-2@barcdaily20200506175543 - | tee >(pigz -3 -p 2 > '/mnt/pve/B2.C4-J/guest_backups//barc/102/daily/20200506175543cephRBD.vm-102-disk-2.img.zz') | tee >({ wc -c; } > /mnt/pve/B2.C4-J/guest_backups//barc/102/daily/20200506175543cephRBD.vm-102-disk-2.img.zz.sha1.size) | sha1sum > /mnt/pve/B2.C4-J/guest_backups//barc/102/daily/20200506175543cephRBD.vm-102-disk-2.img.zz.sha1

Exporting image: 2% complete...
Exporting image: 5% complete...
Exporting image: 8% complete...
Exporting image: 10% complete...
Exporting image: 13% complete...
Exporting image: 16% complete...
Exporting image: 18% complete...
Exporting image: 21% complete...
Exporting image: 24% complete...
Exporting image: 26% complete...
Exporting image: 29% complete...
Exporting image: 32% complete...
Exporting image: 34% complete...
Exporting image: 37% complete...
Exporting image: 40% complete...
Exporting image: 42% complete...
Exporting image: 45% complete...
Exporting image: 48% complete...
Exporting image: 50% complete...
Exporting image: 53% complete...
Exporting image: 56% complete...
Exporting image: 58% complete...
Exporting image: 61% complete...
Exporting image: 64% complete...
Exporting image: 66% complete...
Exporting image: 69% complete...
Exporting image: 72% complete...
Exporting image: 74% complete...
Exporting image: 77% complete...
Exporting image: 80% complete...
Exporting image: 82% complete...
Exporting image: 85% complete...
Exporting image: 88% complete...
Exporting image: 90% complete...
Exporting image: 93% complete...
Exporting image: 96% complete...
Exporting image: 98% complete...
Exporting image: 100% complete...done.
VM 102 - Size 58.58 MiB Uncompressed: 150.00 MiB Compressionratio 1:2
VM 102 - Export initial '/mnt/pve/B2.C4-J/guest_backups//barc/102/daily/20200506175543cephRBD.vm-102-disk-0.img.zz'
VM 102 - excmd: rbd export --rbd-concurrent-management-ops 10 cephRBD/vm-102-disk-0@barcdaily20200506175543 - | tee >(pigz -3 -p 2 > '/mnt/pve/B2.C4-J/guest_backups//barc/102/daily/20200506175543cephRBD.vm-102-disk-0.img.zz') | tee >({ wc -c; } > /mnt/pve/B2.C4-J/guest_backups//barc/102/daily/20200506175543cephRBD.vm-102-disk-0.img.zz.sha1.size) | sha1sum > /mnt/pve/B2.C4-J/guest_backups//barc/102/daily/20200506175543cephRBD.vm-102-disk-0.img.zz.sha1

Exporting image: 1% complete...
Exporting image: 2% complete...
Exporting image: 3% complete...
Exporting image: 4% complete...
Exporting image: 5% complete...
Exporting image: 6% complete...
Exporting image: 7% complete...
Exporting image: 8% complete...
Exporting image: 9% complete...
Exporting image: 10% complete...
Exporting image: 11% complete...
Exporting image: 12% complete...
Exporting image: 13% complete...
Exporting image: 14% complete...
Exporting image: 15% complete...
Exporting image: 16% complete...
Exporting image: 17% complete...
Exporting image: 18% complete...
Exporting image: 19% complete...
Exporting image: 20% complete...
Exporting image: 21% complete...
Exporting image: 22% complete...
Exporting image: 23% complete...
Exporting image: 24% complete...
Exporting image: 25% complete...
Exporting image: 26% complete...
Exporting image: 27% complete...
Exporting image: 28% complete...
Exporting image: 29% complete...
Exporting image: 30% complete...
Exporting image: 31% complete...
Exporting image: 32% complete...
Exporting image: 33% complete...
Exporting image: 34% complete...
Exporting image: 35% complete...
Exporting image: 36% complete...
Exporting image: 37% complete...
Exporting image: 38% complete...
Exporting image: 39% complete...
Exporting image: 40% complete...
Exporting image: 41% complete...
Exporting image: 42% complete...
Exporting image: 43% complete...
Exporting image: 44% complete...
Exporting image: 45% complete...
Exporting image: 46% complete...
Exporting image: 47% complete...
Exporting image: 48% complete...
Exporting image: 49% complete...
Exporting image: 50% complete...
Exporting image: 51% complete...
Exporting image: 52% complete...
Exporting image: 53% complete...
Exporting image: 54% complete...
Exporting image: 55% complete...
Exporting image: 56% complete...
Exporting image: 57% complete...
Exporting image: 58% complete...
Exporting image: 59% complete...
Exporting image: 60% complete...
Exporting image: 61% complete...
Exporting image: 62% complete...
Exporting image: 63% complete...
Exporting image: 64% complete...
Exporting image: 65% complete...
Exporting image: 66% complete...
Exporting image: 67% complete...
Exporting image: 68% complete...
Exporting image: 69% complete...
Exporting image: 70% complete...
Exporting image: 71% complete...
Exporting image: 72% complete...
Exporting image: 73% complete...
Exporting image: 74% complete...
Exporting image: 75% complete...
Exporting image: 76% complete...
Exporting image: 77% complete...
Exporting image: 78% complete...
Exporting image: 79% complete...
Exporting image: 80% complete...
Exporting image: 81% complete...
Exporting image: 82% complete...
Exporting image: 83% complete...
Exporting image: 84% complete...
Exporting image: 85% complete...
Exporting image: 86% complete...
Exporting image: 87% complete...
Exporting image: 88% complete...
Exporting image: 89% complete...
Exporting image: 90% complete...
Exporting image: 91% complete...
Exporting image: 92% complete...
Exporting image: 93% complete...
Exporting image: 94% complete...
Exporting image: 95% complete...
Exporting image: 96% complete...
Exporting image: 97% complete...
Exporting image: 98% complete...
Exporting image: 99% complete...
Exporting image: 100% complete...done.
VM 102 - Size 16.77 GiB Uncompressed: 60.00 GiB Compressionratio 1:3
VM 102 - -------- Copy config --------
VM 102 - -------- Housekeeping --------
End backup 2020-05-06 18:05:01

agent: 1,fstrim_cloned_disks=1,type=virtio
args: -device isa-applesmc,osk="redacted" -smbios type=2 -cpu Penryn,kvm=on,vendor=GenuineIntel,+kvm_pv_unhalt,+kvm_pv_eoi,+invtsc,vmware-cpuid-freq=on,+pcid,+ssse3,+sse4.2,+popcnt,+avx,+aes,+xsave,+xsaveopt,check -device usb-kbd,bus=ehci.0,port=2
balloon: 0
bios: ovmf
boot: c
bootdisk: ide2
cores: 4
cpu: Penryn
efidisk0: cephRBD:vm-102-disk-1,size=1M
ide2: cephRBD:vm-102-disk-2,cache=unsafe,size=150M
machine: q35
memory: 8192
name: macOS
net0: vmxnet3=5A:E6:B3:33:62:46,bridge=vmbr0
numa: 0
ostype: other
sata0: cephRBD:vm-102-disk-0,cache=unsafe,discard=on,size=60G
scsihw: virtio-scsi-pci
smbios1: uuid=293106dc-369e-4d20-86f4-5404bab56f07
sockets: 1
vga: vmware
vmgenid: a5d1e941-bbca-4336-b2fa-3ced02e06e1c

**Comment by lephisto** [comment]
This is pretty explain- and fixable:

This is the Line to blame:

https://github.com/Corsinvest/cv4pve-barc/blob/master/eve4pve-barc#L568

It should include efidisk as well. Change that line to:

```grep -P '^(?:((?:virtio|ide|scsi|sata|mp|efidisk)\d+)|rootfs): ' | \```

And you should be good to go. I will include this in the next release.

**Comment by alyarb** [comment]
grazie, backup is working now for VM-102-Disk-2.

However, if I restore the EFI disk, and change the output name, for example

vm-102-disk-2.img.zz -> cephRBD_HDD/vm-102-disk-5 

This is the output:

ACTION: Restore image
Start restore 2020-06-16 10:58:37 20200616104933cephRBD_HDD.vm-102-disk-2.img.zz
Remove all snapshots
rbd: error opening image vm-102-disk-5: (2) No such file or directory
ERROR: rbd snap purge cephRBD_HDD/vm-102-disk-5
Backup 20200616104933cephRBD_HDD.vm-102-disk-2.img.zz restored in cephRBD_HDD/vm-102-disk-5 with success!
Consider to manually create VM/CT and change config file from backup adapting restored image.
End restore 2020-06-16 10:58:38
0 Bytes restored in 1 Seconds. [0 Bytes/s] [Compressed Size 0 Bytes]
Issuing qm-rescan
rescan volumes...


and rbd ls cephRBD_HDD shows that vm-102-disk-5 does not exist
