### ISSUE TITLE
cache=none disks are ignored

### ISSUE THREAD

**Issue by Tatsu-Kishi** [Corsinvest/cv4pve-barc#68]
If a VM's disk has cache=none it's getting ignored by backup. By the looks of it it's the filter for cdrom in `get_disks_from_config()`:
```
grep -v -P 'cdrom|none'
```
which matches either `cdrom` or `none`, and thus also matches cache=none. Not sure if it's supposed to only filter empty cdrom entries ("none,medium=cdrom") or is just redundant terming.

**Comment by franklupo** [comment]
Hi,
ok verify the problem.

**Comment by mrtwister76** [comment]
Same problem exists for VMs created from CloudInit, as they always have a disk mounted in the cdrom.

I'm looking at commenting this out to get my backups running.
Can you tell me if this will have any adverse effect (i.e. why are we checking for an empty cdrom)?

**Comment by mrtwister76** [comment]
I'm suffering from this too.
It occurs when the cache is explicitly set to **No Cache** in the VM disk settings, as opposed to leaving it as **Default (No Cache**).

If this is there to exclude cdrom entries my first suggestion was negative grepping on 'media=cdrom'.
However, that will exclude cloudinit images, which is something that we'd like to also backup.

An example of the CDRom images are:

a) An ISO mounted in a CD-ROM:
  ide2: local:iso/ubuntu.iso,media=cdrom,size=30480K

b) No ISO mounted in a CD-ROM:
  ide2: none,media=cdrom

c) A cloud-init disk:
  ide2: ceph_vm:vm-104-cloudinit,media=cdrom

Replacing with the following grep should allow cloudinit disks to also be backed up (not tested):

`grep -v -P '(?=.*media=cdrom)(?=.*size=)'`

Any news on a fix?

**Comment by franklupo** [comment]
I'm busy with work.
Can you create a fix?

Best reagrds

**Comment by mrtwister76** [comment]
OK, will take a look.
That previous grep I suggested is no good as some cloudinit disks include their size :(
e.g.
ide2: ceph_vm:vm-2014-cloudinit,media=cdrom,size=4M

**Comment by mrtwister76** [comment]
@franklupo I've submitted the pull request #73 
Please take a look when you can.
